apiVersion: v1
kind: Service
metadata:
  name: azurite
spec:
  type: LoadBalancer
  ports:
  - port: 10000
  selector:
    app: azurite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
      - name: azurite
        image: mcr.microsoft.com/azure-storage/azurite
        command: ["azurite-blob"]
        args: ["--blobHost", "0.0.0.0", "--blobPort", "10000"]
        ports:
        - containerPort: 10000
          name: blob